Country.destroy_all
Category.destroy_all

Country.create(name: "Afghanistan", abbr: "AFG")
Country.create(name: "Albania", abbr: "ALB")
Country.create(name: "Algeria", abbr: "DZA")
Country.create(name: "Angola", abbr: "AGO")
Country.create(name: "Antarctica", abbr: "ATA")
Country.create(name: "Argentina", abbr: "ARG")
Country.create(name: "Armenia", abbr: "ARM")
Country.create(name: "Australia", abbr: "AUS")
Country.create(name: "Austria", abbr: "AUT")
Country.create(name: "Azerbaijan", abbr: "AZE")
Country.create(name: "Bangladesh", abbr: "BGD")
Country.create(name: "Belarus", abbr: "BLR")
Country.create(name: "Belgium", abbr: "BEL")
Country.create(name: "Belize", abbr: "BLZ")
Country.create(name: "Benin", abbr: "BEN")
Country.create(name: "Bermuda", abbr: "BMU")
Country.create(name: "Bhutan", abbr: "BTN")
Country.create(name: "Bolivia", abbr: "BOL")
Country.create(name: "Bosnia and Herzegovina", abbr: "BIH")
Country.create(name: "Botswana", abbr: "BWA")
Country.create(name: "Brazil", abbr: "BRA")
Country.create(name: "Brunei", abbr: "BRN")
Country.create(name: "Bulgaria", abbr: "BGR")
Country.create(name: "Burkina Faso", abbr: "BFA")
Country.create(name: "Burundi", abbr: "BDI")
Country.create(name: "Cambodia", abbr: "KHM")
Country.create(name: "Cameroon", abbr: "CMR")
Country.create(name: "Canada", abbr: "CAN")
Country.create(name: "Central African Republic", abbr: "CAF")
Country.create(name: "Chad", abbr: "TCD")
Country.create(name: "Chile", abbr: "CHL")
Country.create(name: "China", abbr: "CHN")
Country.create(name: "Colombia", abbr: "COL")
Country.create(name: "Costa Rica", abbr: "CRI")
Country.create(name: "Croatia", abbr: "HRV")
Country.create(name: "Cuba", abbr: "CUB")
Country.create(name: "Cyprus", abbr: "CYP")
Country.create(name: "Czech Republic", abbr: "CZE")
Country.create(name: "Democratic Republic of the Congo", abbr: "COD")
Country.create(name: "Denmark", abbr: "DNK")
Country.create(name: "Djibouti", abbr: "DJI")
Country.create(name: "Dominican Republic", abbr: "DOM")
Country.create(name: "East Timor", abbr: "TLS")
Country.create(name: "Ecuador", abbr: "ECU")
Country.create(name: "Egypt", abbr: "EGY")
Country.create(name: "El Salvador", abbr: "SLV")
Country.create(name: "Equatorial Guinea", abbr: "GNQ")
Country.create(name: "Eritrea", abbr: "ERI")
Country.create(name: "Estonia", abbr: "EST")
Country.create(name: "Ethiopia", abbr: "ETH")
Country.create(name: "Falkland Islands", abbr: "FLK")
Country.create(name: "Fiji", abbr: "FJI")
Country.create(name: "Finland", abbr: "FIN")
Country.create(name: "France", abbr: "FRA")
Country.create(name: "French Guiana", abbr: "GUF")
Country.create(name: "French Southern and Antarctic Lands", abbr: "ATF")
Country.create(name: "Gabon", abbr: "GAB")
Country.create(name: "Gambia", abbr: "GMB")
Country.create(name: "Georgia", abbr: "GEO")
Country.create(name: "Germany", abbr: "DEU")
Country.create(name: "Ghana", abbr: "GHA")
Country.create(name: "Greece", abbr: "GRC")
Country.create(name: "Greenland", abbr: "GRL")
Country.create(name: "Guatemala", abbr: "GTM")
Country.create(name: "Guinea Bissau", abbr: "GNB")
Country.create(name: "Guinea", abbr: "GIN")
Country.create(name: "Guyana", abbr: "GUY")
Country.create(name: "Haiti", abbr: "HTI")
Country.create(name: "Honduras", abbr: "HND")
Country.create(name: "Hungary", abbr: "HUN")
Country.create(name: "Iceland", abbr: "ISL")
Country.create(name: "India", abbr: "IND")
Country.create(name: "Indonesia", abbr: "IDN")
Country.create(name: "Iran", abbr: "IRN")
Country.create(name: "Iraq", abbr: "IRQ")
Country.create(name: "Ireland", abbr: "IRL")
Country.create(name: "Israel", abbr: "ISR")
Country.create(name: "Italy", abbr: "ITA")
Country.create(name: "Ivory Coast", abbr: "CIV")
Country.create(name: "Jamaica", abbr: "JAM")
Country.create(name: "Japan", abbr: "JPN")
Country.create(name: "Jordan", abbr: "JOR")
Country.create(name: "Kazakhstan", abbr: "KAZ")
Country.create(name: "Kenya", abbr: "KEN")
Country.create(name: "Kosovo", abbr: "CS-KM")
Country.create(name: "Kuwait", abbr: "KWT")
Country.create(name: "Kyrgyzstan", abbr: "KGZ")
Country.create(name: "Laos", abbr: "LAO")
Country.create(name: "Latvia", abbr: "LVA")
Country.create(name: "Lebanon", abbr: "LBN")
Country.create(name: "Lesotho", abbr: "LSO")
Country.create(name: "Liberia", abbr: "LBR")
Country.create(name: "Libya", abbr: "LBY")
Country.create(name: "Lithuania", abbr: "LTU")
Country.create(name: "Luxembourg", abbr: "LUX")
Country.create(name: "Macedonia", abbr: "MKD")
Country.create(name: "Madagascar", abbr: "MDG")
Country.create(name: "Malawi", abbr: "MWI")
Country.create(name: "Malaysia", abbr: "MYS")
Country.create(name: "Mali", abbr: "MLI")
Country.create(name: "Mauritania", abbr: "MRT")
Country.create(name: "Mexico", abbr: "MEX")
Country.create(name: "Moldova", abbr: "MDA")
Country.create(name: "Mongolia", abbr: "MNG")
Country.create(name: "Montenegro", abbr: "MNE")
Country.create(name: "Morocco", abbr: "MAR")
Country.create(name: "Mozambique", abbr: "MOZ")
Country.create(name: "Myanmar", abbr: "MMR")
Country.create(name: "Namibia", abbr: "NAM")
Country.create(name: "Nepal", abbr: "NPL")
Country.create(name: "Netherlands", abbr: "NLD")
Country.create(name: "New Caledonia", abbr: "NCL")
Country.create(name: "New Zealand", abbr: "NZL")
Country.create(name: "Nicaragua", abbr: "NIC")
Country.create(name: "Niger", abbr: "NER")
Country.create(name: "Nigeria", abbr: "NGA")
Country.create(name: "North Korea", abbr: "PRK")
Country.create(name: "Northern Cyprus")
Country.create(name: "Norway", abbr: "NOR")
Country.create(name: "Oman", abbr: "OMN")
Country.create(name: "Pakistan", abbr: "PAK")
Country.create(name: "Panama", abbr: "PAN")
Country.create(name: "Papua New Guinea", abbr: "PNG")
Country.create(name: "Paraguay", abbr: "PRY")
Country.create(name: "Peru", abbr: "PER")
Country.create(name: "Philippines", abbr: "PHL")
Country.create(name: "Poland", abbr: "POL")
Country.create(name: "Portugal", abbr: "PRT")
Country.create(name: "Puerto Rico", abbr: "PRI")
Country.create(name: "Qatar", abbr: "QAT")
Country.create(name: "Republic of Serbia", abbr: "SRB")
Country.create(name: "Republic of the Congo", abbr: "COG")
Country.create(name: "Romania", abbr: "ROU")
Country.create(name: "Russia", abbr: "RUS")
Country.create(name: "Rwanda", abbr: "RWA")
Country.create(name: "Saudi Arabia", abbr: "SAU")
Country.create(name: "Senegal", abbr: "SEN")
Country.create(name: "Sierra Leone", abbr: "SLE")
Country.create(name: "Slovakia", abbr: "SVK")
Country.create(name: "Slovenia", abbr: "SVN")
Country.create(name: "Solomon Islands", abbr: "SLB")
Country.create(name: "Somalia", abbr: "SOM")
Country.create(name: "Somaliland")
Country.create(name: "South Africa", abbr: "ZAF")
Country.create(name: "South Korea", abbr: "KOR")
Country.create(name: "South Sudan", abbr: "SDS")
Country.create(name: "Spain", abbr: "ESP")
Country.create(name: "Sri Lanka", abbr: "LKA")
Country.create(name: "Sudan", abbr: "SDN")
Country.create(name: "Suriname", abbr: "SUR")
Country.create(name: "Swaziland", abbr: "SWZ")
Country.create(name: "Sweden", abbr: "SWE")
Country.create(name: "Switzerland", abbr: "CHE")
Country.create(name: "Syria", abbr: "SYR")
Country.create(name: "Taiwan", abbr: "TWN")
Country.create(name: "Tajikistan", abbr: "TJK")
Country.create(name: "Thailand", abbr: "THA")
Country.create(name: "The Bahamas", abbr: "BHS")
Country.create(name: "Togo", abbr: "TGO")
Country.create(name: "Trinidad and Tobago", abbr: "TTO")
Country.create(name: "Tunisia", abbr: "TUN")
Country.create(name: "Turkey", abbr: "TUR")
Country.create(name: "Turkmenistan", abbr: "TKM")
Country.create(name: "Uganda", abbr: "UGA")
Country.create(name: "Ukraine", abbr: "UKR")
Country.create(name: "United Arab Emirates", abbr: "ARE")
Country.create(name: "United Kingdom", abbr: "GBR")
Country.create(name: "United Republic of Tanzania", abbr: "TZA")
Country.create(name: "United States of America", abbr: "USA")
Country.create(name: "Uruguay", abbr: "URY")
Country.create(name: "Uzbekistan", abbr: "UZB")
Country.create(name: "Vanuatu", abbr: "VUT")
Country.create(name: "Venezuela", abbr: "VEN")
Country.create(name: "Vietnam", abbr: "VNM")
Country.create(name: "West Bank", abbr: "PSE")
Country.create(name: "Western Sahara", abbr: "ESH")
Country.create(name: "Yemen", abbr: "YEM")
Country.create(name: "Zambia", abbr: "ZMB")
Country.create(name: "Zimbabwe", abbr: "ZWE")

Category.create(name: "Expressions")
Category.create(name: "Sights")

svn = Country.find_by_abbr("SVN")
fra = Country.find_by_abbr("FRA")


p1 = Post.new(content: "Dober dan", category: Category.first)
p2 = Post.new(content: "Eifel Tower", category: Category.last)

svn.posts << p1
svn.save

fra.posts << p2
fra.save


